name: Java CI with JUnit

# Workflow triggers when a push is made to the main branch or a pull request is opened targeting the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Tjekker koden ud fra repoet
      - name: Checkout code
        uses: actions/checkout@v3

      # Sætter Java op
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'
      # Maven
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test with Maven
        run: mvn -B test --file pom.xml
