name: Java CI with JUnit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Tjekker koden ud fra repoet
      - name: Checkout code
        uses: actions/checkout@v3

      # Sætter Java op
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      # Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Test with Maven (Ensure that pom.xml exists in this directory)
      - name: Test with Maven
        run: mvn -B test --file pom.xml
