name: Java CI with JUnit

# Workflow triggers when a push is made to the main branch or a pull request is opened targeting the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Tjekker koden ud fra repoet
      - name: Checkout code
        uses: actions/checkout@v3

      # Sætter Java op
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      # Bygger projektet med Maven eller Gradle (afhængigt af hvad du bruger)
      - name: Build with Maven
        run: mvn clean install

      # Kører tests ved hjælp af Maven
      - name: Run tests
        run: mvn test
